# Generated by Django 4.1.3 on 2022-11-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Today', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
