# Generated by Django 4.1.3 on 2022-11-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Today', '0002_alter_posts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
