# Generated by Django 4.1.3 on 2022-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Today', '0003_posts_image_alter_posts_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.CharField(default='', max_length=800)),
            ],
        ),
    ]
