# Generated by Django 4.1.3 on 2022-11-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Today', '0004_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='image',
        ),
    ]
