# Generated by Django 4.1.3 on 2022-11-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Today', '0005_remove_comments_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
